# Generated by Django 2.1.2 on 2018-10-30 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='birth_city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='birth_district',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='father',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='gender',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='mother',
            field=models.TextField(default=''),
        ),
    ]
