# Generated by Django 2.1.2 on 2018-10-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0002_auto_20181030_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='birth_city',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='birth_district',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='father',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='mother',
            field=models.CharField(max_length=128),
        ),
    ]
