# Generated by Django 2.1.2 on 2018-10-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0003_auto_20181030_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
    ]
