# Generated by Django 2.1.2 on 2018-11-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0007_auto_20181031_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterprofileinfo',
            name='date_of_birth',
        ),
    ]
