# Generated by Django 2.1.2 on 2018-11-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0009_auto_20181102_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofileinfo',
            name='constituency',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
