# Generated by Django 2.1.2 on 2018-11-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0010_candidateprofileinfo_constituency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateVote',
            fields=[
                ('candidate_vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_id', models.CharField(max_length=128)),
            ],
        ),
    ]
